const {chromium}=require('playwright');const assert=require('node:assert/strict');const {questions,score}=require('../sins/data.js');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:390,height:844},acceptDownloads:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8080/sins/');await p.locator('#password-input').fill('9800');await p.locator('.password-btn').click();await p.locator('#start').click();
for(let i=0;i<18;i++){await p.waitForFunction(i=>document.querySelector('.question-number')?.textContent.startsWith(`第 ${i+1} 问`),i);await p.locator('[data-answer="2"]').click();}
await p.locator('#confirm-choice').waitFor();assert.equal(await p.locator('#confirm-choice').isDisabled(),true);assert.match(await p.locator('.progress-info').innerText(),/19 \/ 20/);assert.equal(await p.locator('[data-confirm]').count(),8);
await p.locator('[data-confirm="greed"]').click();await p.locator('#confirm-choice').click();assert.match(await p.locator('.progress-info').innerText(),/20 \/ 20/);await p.reload();await p.locator('#start').click();assert.match(await p.locator('.progress-info').innerText(),/美德侧/);await p.locator('[data-confirm="chastity"]').click();await p.locator('#confirm-choice').click();assert.equal(await p.locator('.sin-name').innerText(),'贪婪');assert.equal(await p.locator('.virtue-name').innerText(),'贞洁');assert.match(await p.locator('.confirmation-explanation').innerText(),/你在同分情境选择中更偏向贪婪/);assert.match(await p.locator('.crown.sin').innerText(),/50/);
await p.locator('[data-day="0"]').check();await p.reload();assert.equal(await p.locator('.sin-name').innerText(),'贪婪');assert.equal(await p.locator('[data-day="0"]').isChecked(),true);
const promise=p.waitForEvent('download');await p.locator('#download').click();const dl=await promise;assert.ok(dl.suggestedFilename().includes('双面档案'));
await p.locator('#reconfirm').click();await p.locator('[data-confirm="both"]').click();await p.locator('#confirm-choice').click();await p.locator('[data-confirm="both"]').click();await p.locator('#confirm-choice').click();assert.equal(await p.locator('.sin-name').innerText(),'共同主倾向');assert.match(await p.locator('.confirmation-explanation').innerText(),/你选择了“都差不多”/);
await p.setViewportSize({width:320,height:740});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await p.locator('#review').click();await p.locator('[data-answer="4"]').click();await p.waitForTimeout(450);const saved=await p.evaluate(()=>JSON.parse(sessionStorage.getItem('sins-virtues-v2')));assert.deepEqual(saved.confirmations,{});
const set=async a=>{await p.evaluate(a=>sessionStorage.setItem('sins-virtues-v2',JSON.stringify({unlocked:true,current:17,answers:a,completed:true,confirmations:{}})),a);await p.reload();};
await set(questions.map(q=>['greed','chastity'].includes(q.dim)?4:0));assert.equal(await p.locator('#confirm-choice').count(),0);assert.equal(await p.locator('.sin-name').innerText(),'贪婪');
await set(questions.map(q=>['greed','wrath','chastity'].includes(q.dim)?4:0));assert.match(await p.locator('.progress-info').innerText(),/19 \/ 19/);assert.equal(await p.locator('[data-confirm]').count(),3);await p.locator('[data-confirm="both"]').click();await p.locator('#confirm-choice').click();assert.equal(await p.locator('.sin-name').innerText(),'贪婪 · 暴怒');
await p.screenshot({path:require('node:path').join(require('node:os').tmpdir(),'sins-preview','confirmed-shared.png'),fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: 18/19/20 question routes, explicit choice, shared leaders, unchanged scores, pending reload, persisted choices, reset on answer edit, exports, mobile and no errors');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1);});
