'use strict';
function section(n,title,body){return `<section class="section-card" id="report-${n}"><h3 class="section-title"><span>${n}</span>${title}</h3>${body}</section>`;}
function paragraphs(s){return `<div class="section-content">${s.split('\n\n').map(p=>`<p>${p}</p>`).join('')}</div>`;}
function list(items){return `<ul class="report-list">${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;}
function names(items){return items.map(p=>p.name).join('、');}
function resultNote(r){return `宗罪主倾向：${names(r.sinLeaders)}。美德主倾向：${names(r.virtueLeaders)}。${r.flat?'本次常规作答选项完全相同，区分度有限；请结合真实经历阅读。':''}`;}
function selectionNote(r){return [{label:'宗罪侧',items:r.tied,leaders:r.sinLeaders},{label:'美德侧',items:r.virtueTied,leaders:r.virtueLeaders}].filter(g=>g.items.length>1).map(g=>`${g.label}：${names(g.items)}认同分相同；${g.leaders.length===1?'你在同分情境选择中更偏向'+names(g.leaders)+'，因此将其作为主结果。':'你选择了“都差不多”，因此保留'+names(g.leaders)+'为共同主倾向。'}雷达保留原始分数，不额外加分。`).join(' ');}
function balance(r){const gap=r.sinMean-r.virtueMean;return Math.abs(gap)<12.5?'双面并行':gap>0?'欲望表达更鲜明':'美德表达更鲜明';}
function pairText(r){return `「${r.primary.name}」提醒你留意${r.primary.need}；「${r.virtuePrimary.name}」提供的行动角度是${r.virtuePrimary.need}。两者可以同时存在，不需要用一种身份抵消另一种。\n\n当${r.primary.name}对应的冲动出现时，先问自己真正想得到什么，再尝试调用${r.virtuePrimary.name}的做法：${r.virtuePrimary.tip}这不是压抑需要，而是为表达需要多准备一种方式。\n\n本次宗罪均值为${r.sinMean}，美德均值为${r.virtueMean}，仅用于概览作答倾向。${r.tied.length>1||r.virtueTied.length>1?'同分情境选择已在结果卡和雷达下方说明；共同主倾向的解读与练习以下仅选取一个示例，不表示先展示者更强。':'这组搭配是本次答案的阅读线索，不是经过验证的组合人格。'}`;}
function plan(r){return [r.primary.plan[0],r.primary.plan[1],r.virtuePrimary.tip,r.primary.plan[3],`练习一句表达：“${r.virtuePrimary.script.replace(/^“|”$/g,'')}”`,r.primary.plan[5],`回看这一周：什么时候「${r.primary.name}」的需要出现了？「${r.virtuePrimary.name}」的做法有没有带来新的选择？写下一个愿意继续的小行动。`];}
function evidence(r){return questions.map((q,i)=>({...q,answer:state.answers[i]})).filter(q=>q.dim===r.primary.id||q.dim===r.virtuePrimary.id);}
function radar(r){
 // Seven right-hand spokes for sins, seven left-hand spokes for virtues.
 const order=['lust','envy','wrath','sloth','greed','gluttony','pride','chastity','temperance','charity','diligence','patience','kindness','humility'];
 const dims=order.map(id=>[...profiles,...virtues].find(p=>p.id===id));
 const pt=(i,value,radius=105)=>{const a=(-90+(i+.5)*360/14)*Math.PI/180;return [190+Math.cos(a)*radius*value,183+Math.sin(a)*radius*value];};
 const points=v=>dims.map((_,i)=>pt(i,v).join(',')).join(' ');
 const half=(start,end)=>`190,183 ${dims.slice(start,end).map((p,j)=>pt(j+start,r.scores[p.id]/100).join(',')).join(' ')} 190,183`;
 return `<svg class="radar" viewBox="0 0 380 366" role="img" aria-label="十四维雷达：左侧七美德，右侧七宗罪。下方提供完整数值表。"><title>七宗罪与七美德独立计分雷达</title><circle cx="190" cy="183" r="145" fill="#191b26"/>${[.25,.5,.75,1].map(v=>`<polygon points="${points(v)}" fill="none" stroke="#464253" stroke-width=".7"/>`).join('')}${dims.map((_,i)=>`<line x1="190" y1="183" x2="${pt(i,1)[0]}" y2="${pt(i,1)[1]}" stroke="#464253" stroke-width=".7"/>`).join('')}<polygon class="sin-polygon" points="${half(0,7)}" fill="#9470ce" fill-opacity=".58" stroke="#b293e6" stroke-width="1.7"/><polygon class="virtue-polygon" points="${half(7,14)}" fill="#aabaca" fill-opacity=".17" stroke="#d4dfeb" stroke-width="1.7"/>${dims.map((p,i)=>{const [x,y]=pt(i,r.scores[p.id]/100),[tx,ty]=pt(i,1,145),[sx,sy]=pt(i,1,122);return `<circle cx="${x}" cy="${y}" r="3.7" fill="${i<7?'#c5aceb':'#dce6f1'}"/><text x="${tx}" y="${ty+4}" text-anchor="middle" fill="#d3d2df" font-size="11" font-family="KaiTi,STKaiti,serif">${p.name}</text><text x="${sx}" y="${sy+3}" text-anchor="middle" fill="${i<7?'#b69dd9':'#acbdce'}" font-size="8">${r.scores[p.id]}</text>`;}).join('')}</svg>`;
}
function crown(p,tied,r,kind){const leaders=kind==='sin'?r.sinLeaders:r.virtueLeaders;return `<article class="crown ${kind}"><div class="crown-label">${kind==='sin'?'欲望主倾向':'美德主倾向'}</div><div class="crown-en">${leaders.length===1?p.en:'SHARED LEAD'}</div><h2 class="result-name ${kind}-name" tabindex="-1">${leaders.length===1?p.name:leaders.length===2?leaders.map(x=>x.name).join(' · '):'共同主倾向'}</h2><div class="crown-score">${r.scores[p.id]}<small> / 100</small></div>${tied.length>1?`<p class="tie-caption">${leaders.length===1?'同分情境选择确认':names(leaders)+' · 你选择了都差不多'}</p>`:''}</article>`;}
function showResult(){
 stopTransition();let r;try{r=score(state.answers,state.confirmations);}catch(_){state.completed=false;state.current=Math.max(0,state.answers.indexOf(null));showQuestion();return;}
 if(r.pending.length){showConfirmation(r);return;}
 state.completed=true;save();const p=r.primary,v=r.virtuePrimary;
 render(`<section class="result-card dual-result"><div class="dossier-topline"><span>NOCTURNE / PERSONAL ARCHIVE</span><span>你的双面档案</span></div><div class="combination"><span>你的双面组合</span><h1>${names(r.sinLeaders)} <i>×</i> ${names(r.virtueLeaders)}</h1><p>理解想要什么，也理解如何回应。</p></div><div class="crown-grid">${crown(p,r.tied,r,'sin')}${crown(v,r.virtueTied,r,'virtue')}</div><p class="balance-line">${balance(r)} <span>· 宗罪均值 ${r.sinMean} · 美德均值 ${r.virtueMean}</span></p></section>
 ${section('01','你的双面坐标',`<p class="radar-subtitle">左侧七美德 · 右侧七宗罪 · 双轴独立计分</p>${radar(r)}<div class="chart-legend"><span>宗罪倾向</span><span>美德倾向</span></div><p class="quiet">图中呈现本次作答认同度；这是一份日常选择的图谱，不是专业人格测量。两组分数可同时高或低，不代表善恶比例。</p>`)}
 <p class="result-note">${resultNote(r)}</p>${selectionNote(r)?`<p class="result-note confirmation-explanation">${selectionNote(r)}</p>`:''}<nav class="report-nav" aria-label="报告章节"><a href="#report-03">双面解读</a><a href="#report-06">完整图谱</a><a href="#report-08">行动指南</a></nav>
 ${section('02','答案中的真实线索',`<p class="quiet">下列回答对应两组最高分的展开示例。每个维度只有1–2道题，线索有限，请结合实际经历阅读。</p>${evidence(r).map(q=>`<div class="evidence"><blockquote>“${q.text}”</blockquote><p>${[...profiles,...virtues].find(d=>d.id===q.dim).name} · 你的选择：<strong>${OPTIONS[q.answer]}</strong></p></div>`).join('')}`)}
 ${section('03','欲望与美德，同时读懂',`<div class="reading-heading">宗罪侧 / ${p.name}</div>${paragraphs(p.analysis)}<div class="reading-heading virtue-heading">美德侧 / ${v.name}</div>${paragraphs(v.analysis)}<p class="quiet">最高分是组内相对位置。若最高分仍偏低，以上内容只作为原型介绍，不说明你具有强烈倾向。</p>`)}
 ${section('04','你的双面，如何一起行动',paragraphs(pairText(r))+`<div class="script-box"><span>可以直接尝试的表达</span><blockquote>${v.script}</blockquote></div>`)}
 ${section('05','把理解带回现实场景',`<h4>欲望中可以利用的力量</h4>${list(p.strengths)}<h4>留意这些代价</h4>${list(p.risks)}${p.scenarios.map(t=>{const [a,b]=t.split('｜');return `<div class="scenario"><strong>${a}</strong>${b}</div>`;}).join('')}<div class="scenario"><strong>调用你的美德资源 · ${v.name}</strong>${v.tip}</div>`)}
 ${section('06','十四面镜子，完整展开',`<p class="quiet">分数是0–100的题目认同度，不是概率或人群排名。点击维度可阅读解读。</p><div class="dimension-columns">${[{title:'七宗罪',items:r.ranked,kind:'sin'},{title:'七美德',items:r.virtueRanked,kind:'virtue'}].map(g=>`<div class="dimension-column ${g.kind}"><h4>${g.title}</h4>${g.items.map(d=>`<details class="other-profile"><summary><span>${d.name}</span><span>${r.scores[d.id]} / 100 ＋</span></summary>${paragraphs(d.analysis)}<div class="scenario"><strong>一个小行动</strong>${d.tip||d.plan[0]}</div></details>`).join('')}</div>`).join('')}</div>`)}
 ${section('07','本次适合从哪里开始',`<p class="section-content">不必追求把宗罪压到零、把美德拉到满分。先挑一个最近反复出现的情境，用「${p.name}」的线索辨认自己的需要，再用「${v.name}」的做法试一次新的回应。</p><div class="scenario"><strong>今天就能做</strong>${v.tip}</div><p class="quiet">如果解读与你不符，可以返回修改答案，或直接跳过不适用的建议。不要用这些分数评价伴侣、同事或决定重大事项。</p>`)}
 ${section('08','七天练习，让选择变得具体',`<p class="quiet">每天挑一个小动作，约5–10分钟。行动清单可以勾选，并随报告保存。</p><div id="plan-count" class="plan-count" role="status">已完成 ${state.checks.filter(Boolean).length} / 7</div>${plan(r).map((t,i)=>`<label class="plan-item"><input type="checkbox" data-day="${i}" ${state.checks[i]?'checked':''}><span><b>DAY ${String(i+1).padStart(2,'0')}</b>${t}</span></label>`).join('')}`)}
 <div class="encourage-box">看见欲望，也看见善意。<br>你不止一种模样。</div><details class="report-details"><summary>计分与内容说明</summary><p>${selectionNote(r)}</p><p>18道常规情境题：宗罪与美德各9题，最高分同分时每侧追加1道确认题，总题数最多20题，十四个维度各有1–2题。选项为0–4分，每维度取均值后乘25。两组各自排序，组内七个维度等权计算均值。同分由用户通过情境选择确认主倾向，选择“都差不多”则保留共同主倾向；确认题不计入雷达分数；“更鲜明”仅指两组均值相差至少12.5分。规则属于创作设定，未经心理测量学验证。</p><p>宗罪与美德独立计分，美德不是100减宗罪。七宗罪与七美德均作为文学意象使用，不作道德或宗教判断、不诊断疾病。“贞洁”在此仅指真诚与尊重关系边界，不评价性经历或身体。答案仅保存于当前标签页。</p></details><div class="navigation"><button class="btn btn-secondary" id="copy">复制报告</button><button class="btn btn-primary" id="download">保存完整报告 ↓</button></div><div class="navigation"><button class="btn btn-secondary" id="review">回看并修改答案</button><button class="btn btn-secondary" id="restart">重新探索</button></div><div class="navigation"><button class="btn btn-secondary" id="home">返回测试首页</button>${r.tied.length>1||r.virtueTied.length>1?'<button class="btn btn-secondary" id="reconfirm">修改同分选择</button>':''}</div>`,'.result-name');
 main.querySelectorAll('[data-day]').forEach(el=>el.onchange=()=>{state.checks[Number(el.dataset.day)]=el.checked;save();document.getElementById('plan-count').textContent=`已完成 ${state.checks.filter(Boolean).length} / 7`;});
 document.getElementById('reconfirm')?.addEventListener('click',()=>{state.confirmations={};state.completed=false;state.checks.fill(false);save();showResult();scrollTop();});
 document.getElementById('restart').onclick=restart;document.getElementById('home').onclick=()=>{showStart();scrollTop();};
 document.getElementById('review').onclick=()=>{state.current=0;state.completed=false;save();showQuestion();scrollTop();};
 document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(reportText());notify('完整报告已复制。');}catch(_){notify('复制暂不可用，请保存完整报告。');}};
 document.getElementById('download').onclick=()=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+reportText()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='七宗罪vs七美德-双面档案.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('已发起报告下载。');};
}
function reportText(){const r=score(state.answers,state.confirmations);return ['七宗罪 vs 七美德 · 双面档案',resultNote(r),selectionNote(r),`${balance(r)} · 宗罪均值 ${r.sinMean} · 美德均值 ${r.virtueMean}`,'\n十四维作答认同度',...[...r.ranked,...r.virtueRanked].map(d=>`${d.name}：${r.scores[d.id]}/100`),'\n双面解读',pairText(r),'\n答案线索',...evidence(r).map(q=>`${q.text}：${OPTIONS[q.answer]}`),...[...r.ranked,...r.virtueRanked].map(d=>`\n${d.name}\n${d.analysis}\n行动建议：${d.tip||d.plan[0]}\n沟通提示：${d.script}${d.strengths?'\n可利用的力量：'+d.strengths.join('；')+'\n留意的代价：'+d.risks.join('；')+'\n生活场景：'+d.scenarios.join('；'):''}`),'\n七天行动清单',...plan(r).map((t,i)=>`${state.checks[i]?'[已完成]':'[待尝试]'} 第${i+1}天：${t}`),'\n18道常规题及最多2道同分确认题，十四维各1–2道常规题；每维度均分×25，组内维度等权平均，两组独立计算，同分通过用户情境选择确认，选择“都差不多”则保留共同主倾向，原始分数不变。','文学主题娱乐探索，未经心理测量学验证，不作道德判断、专业人格测量或医疗评估。'].join('\n\n');}
