const HISTORY_KEY='assessment_xlnl_history_v1';
let answers=[],answerTimer,loadingTimer,answerLock=false;
const byId=id=>document.getElementById(id);
const originalScreen=app.showScreen,originalRender=app.renderQuestion;
app.showScreen=function(id){originalScreen.call(this,id);document.body.dataset.view=id;byId('psycheNav').classList.remove('hidden');byId('quiz-home').hidden=id==='start-screen';window.scrollTo(0,0);};
app.startQuiz=async function(){clearTimeout(answerTimer);answers=new Array(QUESTIONS.length).fill(null);this.state.currentQuestionIndex=0;this.state.score=0;this.showScreen('quiz-screen');this.renderQuestion();};
app.renderQuestion=function(){answerLock=false;originalRender.call(this);const i=this.state.currentQuestionIndex;byId('question-counter').textContent=`第 ${i+1} 题`;byId('question-total').textContent=`共 ${QUESTIONS.length} 题`;byId('previous-question').disabled=i===0;byId('submit-quiz').hidden=i!==QUESTIONS.length-1;byId('submit-quiz').disabled=answers[i]===null;byId('options-container').querySelectorAll('button').forEach((button,index)=>{const selected=answers[i]===index;button.classList.toggle('chosen',selected);button.setAttribute('aria-pressed',String(selected));button.onclick=()=>this.handleAnswer(index);});};
app.handleAnswer=function(index){if(answerLock)return;const i=this.state.currentQuestionIndex;answers[i]=index;this.renderQuestion();if(i<QUESTIONS.length-1){answerLock=true;answerTimer=setTimeout(()=>{this.state.currentQuestionIndex=i+1;this.renderQuestion();},200);}};
function historyItems(){try{const list=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(list)?list.filter(r=>r&&r.payload&&Number.isFinite(r.payload.score)&&Array.isArray(r.payload.chartData)).slice(0,8):[];}catch{return [];}}
function showHistory(){const list=historyItems();if(!list.length){byId('history-status').textContent='还没有保存的报告，完成探索后会出现在这里。';return;}const dialog=byId('history-dialog');dialog.querySelector('.history-list').replaceChildren();list.forEach(item=>{const button=document.createElement('button');button.textContent=`${item.payload.title} · ${item.payload.psychAge} 岁 · ${new Date(item.date).toLocaleDateString()}`;button.onclick=()=>{dialog.close();app.applyResultPayload(item.payload);};dialog.querySelector('.history-list').append(button);});dialog.showModal();}
app.showResult=async function(){if(answers.some(v=>v===null))return;clearTimeout(answerTimer);answerLock=true;byId('submit-quiz').disabled=true;this.state.score=answers.reduce((sum,index,i)=>sum+QUESTIONS[i].options[index].score,0);const result=RESULTS.find(r=>this.state.score>=r.minScore&&this.state.score<=r.maxScore);const payload=buildResultPayload(this.state.score,result,this.state.actualAge);byId('quiz-status').textContent='正在整理你的心理画像…';loadingTimer=setTimeout(()=>{try{localStorage.setItem(HISTORY_KEY,JSON.stringify([{date:Date.now(),payload},...historyItems()].slice(0,8)));}catch{byId('history-status').textContent='浏览器未能保存历史报告，你仍可下载文字报告。';}byId('quiz-status').textContent='';this.applyResultPayload(payload);},800);};
app.restart=async function(){clearTimeout(answerTimer);clearTimeout(loadingTimer);answerLock=false;byId('quiz-status').textContent='';this.showScreen('start-screen');};
function downloadReport(){const text=byId('result-screen').innerText;const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='心理年龄-探索报告.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('DOMContentLoaded',()=>{
 app.init();app.showScreen('start-screen');
 const controls=document.createElement('div');controls.className='quiz-controls';controls.innerHTML='<button id="previous-question" type="button">上一题</button><button id="submit-quiz" class="local-primary" type="button" hidden>生成我的报告</button><p id="quiz-status" role="status"></p>';byId('options-container').after(controls);
 byId('previous-question').onclick=()=>{clearTimeout(answerTimer);if(app.state.currentQuestionIndex>0){app.state.currentQuestionIndex--;app.renderQuestion();}};byId('submit-quiz').onclick=()=>app.showResult();
 byId('start-btn').onclick=()=>{byId('auth-error').textContent='';byId('auth-input').value='';byId('auth-dialog').showModal();byId('auth-input').focus();};
 byId('auth-form').onsubmit=e=>{e.preventDefault();if(byId('auth-input').value.trim()!=='853804'){byId('auth-error').textContent='密码不正确，请重试。';return;}byId('auth-dialog').close();app.startFlow();};byId('auth-input').oninput=()=>byId('auth-error').textContent='';
 const history=document.createElement('div');history.className='local-history';history.innerHTML='<button id="history-btn" type="button">查看历史报告</button><p id="history-status" role="status"></p>';byId('start-screen').append(history);byId('history-btn').onclick=showHistory;
 const historyDialog=document.createElement('dialog');historyDialog.id='history-dialog';historyDialog.setAttribute('aria-label','历史报告');historyDialog.innerHTML='<button class="dialog-close" aria-label="关闭" onclick="this.closest(\'dialog\').close()">×</button><h2>你的探索记录</h2><div class="history-list"></div>';document.body.append(historyDialog);
 const note=document.createElement('p');note.className='radar-note';note.textContent='雷达展示当前画像的预设特征，不是八项独立测量分数。心理年龄为趣味换算，不代表实际发展年龄或能力。';byId('radarChart').parentElement.after(note);
 const exportButton=document.createElement('button');exportButton.className='local-primary export-report';exportButton.textContent='下载文字报告';exportButton.onclick=downloadReport;byId('result-screen').append(exportButton);
});
